services:
  # app:
  #   image: naru-backend
  #   container_name: naru-backend
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
  #     SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
  #     SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
  #   depends_on:
  #     - db

  database:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres-data:
